Route service
Utopian-CashMoney/utopian-airlines pull request #9
Opened 2021-05-02 15:57 UTC by JostenAsercion

2021-05-02 21:04 UTC, Joshua-Podhola requested changes
Revisions required

2021-05-02 21:04 UTC, Joshua-Podhola commented on src/main/resources/application.properties
> +spring.datasource.password=NAg6K0V2guDxAXQC
See #8; merge conflict

2021-05-02 21:04 UTC, Joshua-Podhola commented on src/main/java/com/smoothstack/utopiaairlines/dao/RouteDao.java
> +	List <Route> findByDestinationLike(String destination);
Doesn't work; Origin and Destination are Airport objects, not Strings. Ambiguous whether you're trying to search by IATA or City.

Must either replace `String` type with `Airport` (though I'm not sure how this will behave) or access properties:
`findByOrigin_IataIdLike(String iataId)` - equivilent to Java's `origin.iataID`

2021-05-02 21:04 UTC, Joshua-Podhola commented on src/main/java/com/smoothstack/utopiaairlines/controllers/AdminAirport.java
> + */
Dangling Javadoc comment

2021-05-02 21:04 UTC, Joshua-Podhola commented on src/main/java/com/smoothstack/utopiaairlines/controllers/AdminRoute.java
> +			return routeAdminService.searchById(id).get();
Unsafe to call `get()` on an optional without checking for present object with `isPresent()`. Should instead use `orElse(null)` or check with `isPresent()` first, else an exception will be thrown and the user will simply get nothing.

2021-05-02 21:04 UTC, Joshua-Podhola commented on src/main/java/com/smoothstack/utopiaairlines/dao/AirportDao.java
> +	List<Airport> findByIataIdLike(String iataId);
I'd consider not using Like in this case.

2021-05-02 21:04 UTC, Joshua-Podhola commented on src/main/java/com/smoothstack/utopiaairlines/services/AirportAdminService.java
> +	 airportDAO.findByCityLike(city); }
Aside from the ugly formatting, `findByCityLike(...)` will only return exact matches because you aren't using a SQL pattern and instead just passing the user input directly.

2021-05-02 21:04 UTC, Joshua-Podhola commented on src/main/java/com/smoothstack/utopiaairlines/services/AirportAdminService.java
> +		return airportDAO.findByIataIdLike(IataId);
Why not use `getById(...)`? IATAs are unique as they're the primary key. No need to search for a list that will always be of size 1.

2021-05-02 21:04 UTC, Joshua-Podhola commented on src/main/java/com/smoothstack/utopiaairlines/services/RouteAdminService.java
> +	 * @param iata    the new iata code for the route origin
No parameter matching "iata"

2021-05-02 21:04 UTC, Joshua-Podhola commented on src/main/java/com/smoothstack/utopiaairlines/services/RouteAdminService.java
> +			Optional.empty();
This creates an empty Optional and then does nothing with it. This doesn't do anything.

2021-05-03 00:30 UTC, JostenAsercion commented on src/main/java/com/smoothstack/utopiaairlines/controllers/AdminRoute.java
> +			return routeAdminService.searchById(id).get();
Would this work?
 `	@GetMapping("/id/{id}")
	public Route searchById(@PathVariable("id") Integer id) {
		if (routeAdminService.searchById(id).isPresent())
			return routeAdminService.searchById(id).get();
		else {
			return null;
		}
	}`

2021-05-03 04:18 UTC, Joshua-Podhola approved these changes

2021-05-03 04:56 UTC, merged